### ISSUE TITLE
RUIANDownloader ValueError: could not convert string to float: y, 23:59:56.596

### ISSUE THREAD

**Issue by raugustyn** [vugtk21/RUIANToolbox#181]
From karel.mrenca@gmail.com:

Dobry vecer,
nasel jsem Vas software RUIANDownloader. Je to presne to co jsem hledal;o) Jenom pri  stahovani mi dnes zapsal do logu nize uvedenou chybu. Nemate prosim napad co delam spatne? Dekuji a omlouvam se za muj mozna hloupy dotaz. Ale spis znam SQL nez programovani. Mejte se Mrenca

Traceback (most recent call last):
  File "C:\RUIAN\ruian tool\RUIANToolbox-master\RUIANDownloader\RUIANDownload.py", line 519, in <module>
    main()
  File "C:\RUIAN\ruian tool\RUIANToolbox-master\RUIANDownloader\RUIANDownload.py", line 509, in main
    downloader.download()
  File "C:\RUIAN\ruian tool\RUIANToolbox-master\RUIANDownloader\RUIANDownload.py", line 431, in download
    self.buildIndexHTML()
  File "C:\RUIAN\ruian tool\RUIANToolbox-master\RUIANDownloader\RUIANDownload.py", line 284, in buildIndexHTML
    calcSumValues()
  File "C:\RUIAN\ruian tool\RUIANToolbox-master\RUIANDownloader\RUIANDownload.py", line 238, in calcSumValues
    time = float(info.downloadTime[:len(info.downloadTime) - 1])
ValueError: could not convert string to float: y, 23:59:56.596

**Comment by raugustyn** [comment]
hm, na čistej počítač jsem nainstaloval PostGres, PostGIS, Python. Rozbalil RÚIAN Toolbox, do něj stáhnul knihovnu VFR. Download proběhl oky, import zatím běží. Tak uvidíme.

OSGEO4W home is C:\Users\raugustyn\Desktop\RUIANToolbox-master\OSGeo4W_vfr\ 

--------------------------------------------------------------------------------

6254 VFR files will be processed...

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

Processing 20150531_ST_UKSH.xml.gz (1 out of 6254)...

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

EPSG 5514 defined in DB

--------------------------------------------------------------------------------

Processing layer Obce                 ...          0 features added
Processing layer Mop                  ...          0 features added
Processing layer Momc                 ...          0 features added
Processing layer CastiObci            ...          0 features added
--------------------------------------------------------------------------------

Time elapsed: 4 sec

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

Processing 20150531_OB_500011_UKSH.xml.gz (2 out of 6254)...

--------------------------------------------------------------------------------

Processing layer Obce                 ...          1 features added
Processing layer Mop                  ...          0 features added
Processing layer Momc                 ...          0 features added
Processing layer CastiObci            ...          1 features added
Processing layer Ulice                ...         18 features added (1 without geometry)
Processing layer StavebniObjekty      ...        881 features added (1 without geometry)
Processing layer AdresniMista         ...        735 features added
--------------------------------------------------------------------------------

Time elapsed: 1 sec

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------

Processing 20150531_OB_500020_UKSH.xml.gz (3 out of 6254)...

--------------------------------------------------------------------------------

Processing layer Obce                 ...          1 features added
Processing layer Mop                  ...          0 features added
Processing layer Momc                 ...          0 features added
Processing layer CastiObci            ...          2 features added
Processing layer Ulice                ...          0 features added
Processing layer StavebniObjekty      ...        540 features added (5 without geometry)
Processing layer AdresniMista         ...        376 features added (6 without geometry)
--------------------------------------------------------------------------------

Time elapsed: 1 sec

**Comment by raugustyn** [comment]
Tak koukám na tu chybovou hlášku, Vám se zastavilo už stahování dat...
